# Horizontal Pod Autoscaler

kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2

metadata:
  name: bankapp-hpa
  namespace: bankapp

spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: bankapp-deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60

